# Generated by Django 2.2.3 on 2019-08-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=4)),
                ('runtime', models.TimeField()),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
    ]
