# Generated by Django 2.2.3 on 2019-08-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('developer', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('cover_art_url', models.CharField(max_length=500)),
                ('igdb_id', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
