# Generated by Django 2.2.3 on 2019-08-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0002_auto_20190807_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='igdb_id',
            field=models.CharField(max_length=8),
        ),
    ]
