# Generated by Django 2.2.3 on 2019-08-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0006_auto_20190808_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='on_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
